### PR TITLE
Add star rating extension

### PR DESCRIPTION
**Pull request by arthuro555**
Adds the star rating extension by @Entr0py404 .
I reviewed and tested it.

### CODE REVIEW

**Comment by Entr0py404** [comment]
Added missing total stars expression
[StarRating-0.0.2.zip](https://github.com/4ian/GDevelop-extensions/files/6642921/StarRating-0.0.2.zip)

**Comment by Silver-Streak** [comment]
@4ian This appears to be pending final review. Let us know if there's a better way to ping these as ready.

**Comment by Bouh** [comment]
image

**Comment by 4ian** [comment]
Looks great, thanks all!

**Pull request merged**
