### PR TITLE
Add extension Auto Typing

### PR DESCRIPTION
**Pull request by Bouh**
Continue here @4ian @westboy31.
@4ian the extension is good to me,  if you want check :)

Here an example running the extension.
[exemple_autotyping.zip](https://github.com/4ian/GDevelop-extensions/files/5448107/exemple_autotyping.zip)

### CODE REVIEW

**Comment by westboy31** [comment]
this is the same extention with correction of sentences :
[AutoTyping.zip](https://github.com/4ian/GDevelop-extensions/files/5459554/AutoTyping.zip)

I agree that it's better to use it as behavior , this is how it's look like : 
[AutoTyping_behavior.zip](https://github.com/4ian/GDevelop-extensions/files/5459602/AutoTyping_behavior.zip)

but we have the functions implemented two times (two behavior one for BBtext and the other for text) , the only way i see to avoid this is to use any_object in parameters but it could occasion bugs if user choses sprite or something else .

**Comment by 4ian** [comment]
> but we have the functions implemented two times (two behavior one for BBtext and the other for text) , the only way i see to avoid this is to use any_object in parameters but it could occasion bugs if user choses sprite or something else .

Yeah it's unfortunate to have to write the behavior twice, but it's no big deal and better this way :) 
I think having the behavior is a bit more intuitive (what do you think @Bouh?), thanks for doing it!

There are two thing that I'd like to understand:
1. When I change the text with a trigger once, it works ok :) But if I try to change the text *while* it's being typed, it starts to glitch, displaying the full text followed by some part of the text being typed.
  - See this example I made: [Example.json.zip](https://github.com/4ian/GDevelop-extensions/files/5464148/Example.json.zip)
  - This is because you're adding a character one by one. I think this is overcomplicated things here:
    image
    Instead, use `SubStr` to choose a portion of the text to write (which is _txt_buffer), starting at position 0 and finishing just after the write index (the `1 +` is important): 
    image

2. You're using a scene timer with the object name. This has the problem that this won't work with more than one object.
  - => Can you use a timer of the object rather? I think you overcomplicated this by using a scene timer. Unless I missed something, use an object timer called "Write timer" or something like "Autotyping Write Timer" (so you're sure no one else will use your timer :)) and it will work for multiple object independently.

3. Finally, even with the fix of `SubStr` to avoid glitches while changing the text, if we try to change the text while it's written, we have potential the text being flashed, before being replaced by the auto typed text the next time the timer reaches the next character to be added. 
  - How to solve this? If you're in the state of writing (i.e: _write_index is less than the length of the text to type), then always set the text. Then increment the _write_index only when the timer reaches the interval. Like this:
    image

With this, you have a behavior that:
- works even without a trigger once! In my example, I used a click/touch condition.
- the text won't stop or glitch before it's fully finished. If you try to change the text, it will only work once the typing is finished.
- with the timer fix, it should work for multiple objects

Let me know if you can do these three changes in both behaviors. This is my example with the extension modified to have the fix #1 and #3 done on the text object: 
[Example partially fixed.json.zip](https://github.com/4ian/GDevelop-extensions/files/5464298/Example.partially.fixed.json.zip)

If you can do the timer fixes, and do the equivalent changes in the BBText object, we should then be ready to publish this very nice extension! 👍👍

**Comment by Bouh** [comment]
> I think having the behavior is a bit more intuitive (what do you think @Bouh?)

This is better indeed, the users will have no surprises with the startup action at least ^^
I still see people asking why the actions don't work, because the actions are in an sub-events with conditions doesn't work hehe.

**Comment by westboy31** [comment]
Well seen it's way better like that:
[AutoTyping.zip](https://github.com/4ian/GDevelop-extensions/files/5465496/AutoTyping.zip)

exemple to check the whole extension:
[exemple.zip](https://github.com/4ian/GDevelop-extensions/files/5465527/exemple.zip)

**Comment by 4ian** [comment]
Thanks! I did a final update of some descriptions, it's now added (ac1da141ceb919bbc6e0beb4f5523b137162e669) and available :)

**Comment by 4ian** [comment]
Closing this now, thanks @westboy31 for this nice extension and @Bouh for your help!

Will be very very useful for a lot of games!

**Pull request closed without merging**
