### PR TITLE
Improve fire bullet behavior

### PR DESCRIPTION
**Pull request by Bouh**
- Add angle on bullet.
Useful for bullet non circular.
Issue encounter in live
https://youtu.be/t1EmmPh3YPY?t=3326

- Update header

### CODE REVIEW

**Comment by Bouh** [comment]
Ready to review!

**Comment by Bouh** [comment]
Ready to merge, nothing else to do, i've updated all files too ! :)

**Comment by Bouh** [comment]
@4ian can you merge?
Or i can take care of extension and merge if you prefer, make a review for extension is not very complicated.
In this case i need access for it.

**Comment by 4ian** [comment]
Thanks for pinging me, merging now! I can add you as a collaborator if needed for other extensions?

**Comment by Bouh** [comment]
> Thanks for pinging me, merging now! I can add you as a collaborator if needed for other extensions?

Yes yes for sure! I'm happy to help!

**Pull request merged**
